@startuml
autonumber
actor 用户

== 文本集构建 ==
打包工具 -> 打包工具: 项目打包构建
打包工具 --> 文本集构造工具: 页面文本集构造

文本集构造工具 --> 文本集构造工具: 扫描路由路径
文本集构造工具 --> 文本集构造工具: 处理SFC文件
文本集构造工具 --> 文本集构造工具: 处理JS文件
文本集构造工具 --> 文本集构造工具: 收集文案
文本集构造工具 --> 文本集构造工具: 生成路由文件

== 搜索组件初始化 ==
文本集构造工具 --> 搜索组件: 提供页面文本集
搜索组件 --> 搜索组件: 组件初始化

== 用户搜索 ==
用户 --> 搜索组件: 使用搜索
搜索组件 --> 搜索算法: 对关键字分词

loop 遍历分词集合
    搜索算法 --> 搜索算法: 模糊查询
end

搜索算法 --> 搜索组件: 返回搜索结果
搜索组件 --> 搜索组件: 渲染搜索结果
用户 --> 搜索组件: 点击快捷跳转

@enduml
