@startuml

package 全局搜索 {
    node 文本集构造工具 {
        [文案收集]
        [路由构造]
        [vue组件处理]
        [JS代码处理]
    }
    
    note top of 文本集构造工具
    页面文本集：页面文本与路由的映射关系，
    数据结构为扩展的 Vue Router 结构
    end note

    node 搜索组件 {
        [UI逻辑处理]
        [搜索结果展示]
        [搜索数据源构造]
    }
    
    note right of 搜索数据源构造
    搜索数据源构造：处理页面文本集或自定义数据
    （如后端数据），统一数据结构，作为搜索数据源
    end note

    node 搜索算法 {
        [分词搜索算法]
        [模糊搜索算法]
        [结果排序]
    }

    note right of 分词搜索算法
    分词搜索算法：对关键字分词后遍历生成的分词集合，
    进行模糊查询后返回搜索结果
    end note
}

文本集构造工具 -down-> 搜索组件 : 提供文本集
搜索算法 -up-> 搜索组件 : 提供搜索结果

@enduml
