@startuml

package 单文件替换 {

    node 打包构建 {
        [构建过程改造]
        [打包配置改造]
    }
    
    note top of 打包构建
    生成两份产物：未混淆压缩&带静态版本标识的代码;
    end note

    node patch文件构建 {
        [打包产物DIFF]
        [patch文件生成]
    }
    
    note right of patch文件构建
    利用git命令切换工作区，执行两次构建，得到diff后
    【未混淆压缩&带静态版本标识的代码】的patch文件
    end note

    node 补丁应用 {
        [备份文件]
        [应用补丁]
        [文件预处理]
        [生产文件替换]
    }

    note right of 补丁应用
    未混淆压缩&带静态版本标识进行补丁应用后， 
    执行混淆压缩和替换静态版本号为动态版本号
    end note

    node 公共方法 {
        [版本号添加]
        [代码压缩混淆]
        [md5计算]
        [路径处理]
    }
}

打包构建 --> patch文件构建 : 提供基线代码
patch文件构建 --> 补丁应用 : 提供patch文件
打包构建 --> 公共方法 : 调用
patch文件构建 --> 公共方法 : 调用
补丁应用 --> 公共方法 : 调用

@enduml
