@startuml
autonumber

actor 开发者

participant "打包构建" as 打包构建
participant "patch文件构建" as patch构建
participant "应用补丁" as 补丁应用

== 打包构建 ==
开发者 -> 打包构建 : 构建未混淆压缩&带静态版本标识的代码
note right of 打包构建 : 在构建过程中插入静态版本标识
打包构建 -> 打包构建 : 另存为【未混淆压缩&带静态版本标识的代码】

打包构建 -> 打包构建 : 执行混淆压缩和替换静态版本号为动态版本号
打包构建 -> 打包构建 : 另存为【混淆压缩&带动态版本标识的代码】

== patch文件构建 ==
开发者 -> patch构建 : 初始构建（未包含修改）
开发者 -> patch构建 : 二次构建（包含修改）
patch构建 -> patch构建 : 临时目录中diff两次构建产物
patch构建 -> patch构建 : 生成patch文件

alt 流程异常
    patch构建 -> 开发者 : git回退并删除临时目录，提示程序退出
end

== 应用补丁 ==
补丁应用 -> 补丁应用 : apply patch操作
alt patch冲突
    补丁应用 -> 开发者 : 提示人工介入，提示程序退出
end

补丁应用 -> 补丁应用 : 执行混淆压缩和替换静态版本号为动态版本号
补丁应用 -> 补丁应用 : 替换生产文件

@enduml
