@startuml
left to right direction
skinparam linetype ortho

package CLI {
    [参数解析]
}

package 前端控制台 {
    [配置页面]
    [概览页面]
}

package 本地服务 {
    [接口路由]
    [autoFix服务调用]

    [接口路由] -> [autoFix服务调用] : 传递配置参数
}

package autoFix服务 {

    node 数据采集上报 {
        [数据采集]
        [数据上报]
    }
    node 扫描模块 {
        [过滤处理]
        [文件集合构建]
    }

    node 合并构建模块 {
        [AI Review]
        [创建新分支]
        [AI构建问题集合]
        [创建合并请求]
        [消息集合构建]
    }

    node 通知模块 {
        [消息处理]
    }

    node 日志模块 {
        [持久化日志]
    }

    node 全局配置 {
        [动态配置管理]
    }

    [数据采集] -down-> 扫描模块 : 采集数据
    [数据采集] -down-> 合并构建模块 : 采集数据
    
    扫描模块 -down-> 合并构建模块 : 传递文件集合
    合并构建模块 -down-> 通知模块 : 传递消息集合
}

cloud 数据运营 {
    [数据处理]
    [数据接口]
    [前端数据展示]

    [数据接口] -down-> [数据处理] : 调用
    [前端数据展示] -> [数据接口] : 请求运营展示数据
}

CLI -up-> 前端控制台 : 唤起
[配置页面] -down-> [接口路由] : 传递配置参数
[数据上报] -down-> [概览页面] : 上报运行数据
[autoFix服务调用] -down-> autoFix服务 : 调用服务
[数据上报] -down-> [数据处理] : 上报运营数据
[autoFix服务调用] -down-> 全局配置 : 更新配置

@enduml