@startuml

autonumber

actor 开发人员

开发人员 -> 前端控制台: 配置服务运行参数

前端控制台 -> 本地服务: 解析服务运行参数

本地服务 -> 扫描模块: 调用autoFix服务

group autoFix服务
    扫描模块 -> gitlab: 获取仓库代码

    扫描模块 -> 合并构建模块: 输入待扫描代码
    note left: gitlab仓库二进制路径集合

    group 合并构建流程
        合并构建模块 -> 合并构建模块: AI review
        note left
        1、敏感词替换
        2、输出处理结果：包含问题分类、改进方案、
            文件路径、改动内容
        end note
        合并构建模块 -> 合并构建模块: 创建新分支
        合并构建模块 -> 合并构建模块: 提交改动到新分支
        note left
        1、敏感词还原
        2、AI构建合并详情：包含问题标签、问题描述、
        改动内容、改动范围、文件路径
        end note
        合并构建模块 -> 合并构建模块: 创建合并请求
    end

    合并构建模块 -> 消息提醒模块: 输入合并请求
    note left: 包含合并描述、代码改动、\n分支信息、合并请求链接

    消息提醒模块 -> 消息提醒模块: 创建合并请求提醒消息
    note left: 包含合并请求链接、合并请求摘要、审核人
end

消息提醒模块 -> 开发人员: 消息提醒

开发人员 -> gitlab: 合并改动

@enduml

